# Generated by Django 4.2 on 2023-04-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=25, verbose_name='Слово')),
                ('translate', models.CharField(max_length=50, verbose_name='Перевод')),
            ],
        ),
    ]
