# Generated by Django 4.1.7 on 2023-04-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_lessons_alter_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='date',
            field=models.CharField(default=0, max_length=25, verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessons',
            name='rang',
            field=models.CharField(default=1, max_length=25, verbose_name='Сложность'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessons',
            name='lesson',
            field=models.TextField(verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Урок'),
        ),
    ]
