# Generated by Django 4.1.7 on 2023-04-24 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_lessons_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='data',
        ),
        migrations.AddField(
            model_name='lessons',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
